### ISSUE TITLE
Stopped working after some time ( python3 )

### ISSUE THREAD

**Issue by ghost** [gregmalcolm/python_koans#152]
While i was working on a about_strings, i got stuck on escaping double quotes / triple quotes, and the whole thing just stopped working ? when i run run.sh i get this : 

    Traceback (most recent call last):
      File "contemplate_koans.py", line 35, in <module>
        Mountain().walk_the_path(sys.argv)
      File "/home/noirchrome/python_koans/python3/runner/mountain.py", line 14, in __init__
        self.tests = path_to_enlightenment.koans()
      File "/home/noirchrome/python_koans/python3/runner/path_to_enlightenment.py", line 62, in koans
        return koans_suite(names)
      File "/home/noirchrome/python_koans/python3/runner/path_to_enlightenment.py", line 51, in koans_suite
        tests = loader.loadTestsFromName(name)
      File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
        module = __import__(module_name)
      File "/home/noirchrome/python_koans/python3/koans/about_strings.py", line 93
        self.assertEqual("""\n""", string)
                                         ^
    SyntaxError: unexpected character after line continuation character

**Comment by csuttles** [comment]
It might help to take a look at line 93 of your 'about_strings.py' and check your edits with `git diff` :)

**Comment by kjc** [comment]
That error usually means you have an extra `\` (backslash, the line continuation character) somewhere nearby.

The closest I could get to reproducing your error was by putting the extra backslash on [line 93](https://github.com/gregmalcolm/python_koans/blob/master/python3/koans/about_strings.py#L93) itself:

        self.assertEqual("""\n"""\, string)

But then it should appear in the stacktrace:

    Traceback (most recent call last):
      File "contemplate_koans.py", line 35, in <module>
        Mountain().walk_the_path(sys.argv)
      File "/home/kjc/tmp/koans/python3/runner/mountain.py", line 14, in __init__
        self.tests = path_to_enlightenment.koans()
      File "/home/kjc/tmp/koans/python3/runner/path_to_enlightenment.py", line 62, in koans
        return koans_suite(names)
      File "/home/kjc/tmp/koans/python3/runner/path_to_enlightenment.py", line 51, in koans_suite
        tests = loader.loadTestsFromName(name)
      File "/usr/lib64/python3.1/unittest.py", line 1265, in loadTestsFromName
        module = __import__('.'.join(parts_copy))
      File "/home/kjc/tmp/koans/python3/koans/about_strings.py", line 93
        self.assertEqual("""\n"""\, string)
                                          ^
    SyntaxError: unexpected character after line continuation character

But that's the sort of thing to look for.  I'd look on the nearby lines as well.  Does this help?

(If you need more help, we'd need to see your whole `test_most_strings_interpret_escape_characters` function.)

**Comment by gregmalcolm** [comment]
Looks like this conversation petered out 2 years ago so I'm just going go ahead and close up on it. Feel free to reopen though if theres still relevance to be had!
